### ISSUE TITLE
space in MQTT password

### ISSUE THREAD

**Issue by ferra-andre** [andrewjfreyer/monitor#127]
Hi, I think there is a problem when the MQTT broker password contain a space.
Works great on previous version, but after I've update to the latest release the problem shows up, you can see below:

```
====================== DEBUG ======================
starting monitor.sh (v. 0.2.028)...
> removing web request caches
> removing public name cache
> generic bluetooth beacon, ibeacon, and known beacon address reporting mode enabled
> report all scan results mode enabled
> preference: using default mqtt protocol version
warning: variable mqtt_publisher_identity does not appear in: mqtt_preferences. using hostname: raspberrypi.
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> 38:53:9C:14:54:0F publishes to: monitor/raspberrypi/38:53:9C:14:54:0F (has not previously connected to hci0)
> 68:AB:1E:1B:B5:7A publishes to: monitor/raspberrypi/68:AB:1E:1B:B5:7A (has not previously connected to hci0)
> 5C:96:9D:8E:05:BA publishes to: monitor/raspberrypi/5C:96:9D:8E:05:BA (has not previously connected to hci0)
================== BEGIN LOGGING ==================
Error: Unknown option 'XX'.
```

In `mqtt_preferences` file I've this: `mqtt_password="abcde XX"`

**Comment by andrewjfreyer** [comment]
Probably an escaping issue. I’ll fix and push new update.

**Comment by andrewjfreyer** [comment]
Yup. Should be addressed in the latest beta. Please comment to reopen this issue if you see it again. 

Thanks!

**Comment by ferra-andre** [comment]
unfortunately, the problem still there (even with version 0.2.030).

**Comment by andrewjfreyer** [comment]
Yes, there was another bug that I have been chasing down - should be fixed now.

**Comment by ferra-andre** [comment]
Thank you @andrewjfreyer, now works fine!

I keep getting this error, but I don't think is related: 
`[CMD-INST]    [fail mqtt] topic: Connection Refused: not authorised. data: Connection Refused: not authorised. (x60)`

**Comment by andrewjfreyer** [comment]
that's unusual, but I think I know the cause. I'll push an update.

**Comment by andrewjfreyer** [comment]
Update to 0.2.034 and let me know if you're still seeing these errors. Thanks!

**Comment by ferra-andre** [comment]
It seems there are gone now, thank you!

I saw that the `/device_tracker` topic send the default message and not the `$device_tracker_message` variable.

**Comment by andrewjfreyer** [comment]
Ooff - catching bugs right and left! pushed 0.2.035
